### ISSUE TITLE
Sync 0.3 et Geonature - Questions de fonctionnement

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_core#10]
Nous avons installé Geonature 2.3.2
En installant Sync 0.3, j'ai l'impression que la version 2.3.2 n'intègre pas les paginations de routes, **est-ce le cas?**
Dans notre cas, ça ne fonctionne pas si je mets dans les paramètres page_max_retry > 1 mais je peux charger mes 5000+ taxons en mettant page_max_retry=1 et page_size = 6000
Par contre je me pose des questions sur mon color_taxon qui pourrait être très gros

Autre question: dans l'idéal, j'aimerai que les agents se loggent sur leur mobile dans sync avec leur nom d'utilisateur. Quelles autorisations minimales faut-il leur donner dans le cruved pour qu'ils puissent télécharger tout ce qu'il faut dans Sync. Pour épurer au maximum leur interface web geonature, je ne leur donne aucun droit sur metadonnées, admin mais j'ai l'impression que c'est ça qui coince.
@camillemonchicourt Comment ferez vous aux Ecrins ? Utiliser un compte générique pour la synchronisation?

**Comment by TheoLechemia** [comment]
> En installant Sync 0.3, j'ai l'impression que la version 2.3.2 n'intègre pas les paginations de routes, est-ce le cas?

Non uniquement sur la branche develop

**Comment by camillemonchicourt** [comment]
Concernant le fonctionnement, oui il est important que les agents utilisent leur compte individuel et on fonctionnera comme ça au PNE.
Normalement les droits qui leur permettent de saisir dans Occtax-web doivent être suffisants pour Occtax-mobile mais à vérifier.

Chez nous les agents ont un CRUVED GeoNature : 

Créer (C) : 3
Lire (R) : 3
Mettre à jour (U) : 1
Valider (V) : 0
Exporter (E) : 2
Supprimer (D) : 1

**Comment by ClaireLagaye** [comment]
> > En installant Sync 0.3, j'ai l'impression que la version 2.3.2 n'intègre pas les paginations de routes, est-ce le cas?
> 
> Non uniquement sur la branche develop

@TheoLechemia 
Est-ce qu'une nouvelle release de Geonature est prévue pour intégrer les nouvelles routes et les paginations? Ou est-ce que tu penses qu'il faudrait que je me mette sur la branche develop (mais ça je n'ai jamais fait)

**Comment by TheoLechemia** [comment]
Pas dans l’immédiat.
La démarche est la même, il faut juste remplacer le X.Y.Z de la version par `develop`

**Comment by camillemonchicourt** [comment]
Oui sachant que la pagination des taxons est côté TaxHub, donc c'est aussi de TaxHub qu'il faut installer la branche ``develop`` pour pouvoir tester.
Pas souhaitable en production car c'est en mouvement, donc seulement pour des tests sur serveurs de tests.

**Comment by ClaireLagaye** [comment]
J'ai installé Geonature et Taxhub en version develop sur mon serveur mais je pense qu'il y a aussi des modifications à faire en bdd . Est-ce que ce script suffit?
data/migrations/2.3.2to2.3.3.sql ?

**Comment by camillemonchicourt** [comment]
Salut, c'est en plein chantier les branches "Develop", donc il faut pas faire ça en production pour le moment.
Mais oui, si tu as fait une MISE A JOUR, pour créer la table qui liste les applications mobiles c'est dans ce script : 

https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.3.2to2.3.3.sql#L60-L75

Et le contenu de la table sur le serveur DEMO : 
1;"OCCTAX";"static/mobile/occtax/occtax-0.3.0-pne-debug.apk";"''";"fr.geonature.occtax";"1660"
2;"SYNC";"static/mobile/sync/sync-0.2.8-pne-debug.apk";"";"fr.geonature.sync";"2280"

Et si tu veux tester le pilotage des versions des applications mobiles et de leurs configurations, il faut mettre les APK et settings.json sur le serveur dans ``/home/myuser/geonature/backend/static/mobile``.
Dans un dossier par application, exemple pour SYNC : 
![image](https://user-images.githubusercontent.com/4418840/82023083-fdc01300-968d-11ea-9a74-dfe9e17727b4.png)
Exemple pour OCCTAX : 
![image](https://user-images.githubusercontent.com/4418840/82023217-36f88300-968e-11ea-9865-76148108b302.png)

Dans tous les cas, le fichier de configuration sur le serveur doit être nommé ``settings.json``

Pour TaxHub, il n'y a pas de modification de la BDD donc pas de migration SQL à passer.

**Comment by ClaireLagaye** [comment]
Super merci @camillemonchicourt 
Je commence à y voir plus clair, je progresse petit à petit.
J'ai maintenant un serveur de test en version develop avec pleins de données qui fonctionne et ma route fonctionne
http://5.196.209.136/geonature/api/gn_commons/t_mobile_apps
J'ai vu sur votre serveur de demo que vous n'aviez plus les paramètres page_size et page_max_retry dans les settings de l'appli Sync, c'est normal?
Les fichiers de settings n'ont pas bougé sinon?

**Comment by camillemonchicourt** [comment]
OK super. Ouais on n'a pas encore ajusté ces paramètres.
