### ISSUE TITLE
Remontée des couleurs de taxons (Sync 0.3)

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_core#11]
Je viens de tester Sync et Occtax sur un nouveau serveur de test à jour des nouvelles routes
J'ai installé les applications mobiles.
Je n'ai plus aucune remontée pour les couleurs de taxons dans Occtax.
Comment est-ce possible de le tester?

**Comment by camillemonchicourt** [comment]
Oui c'est une partie que je ne vois pas bien clairement actuellement.
Mais ça avait été discuté et précisé au niveau d'Occtax-mobile : https://github.com/PnX-SI/gn_mobile_occtax/issues/23#issuecomment-571751295

Il faut extraire un fichier GeoJSON de ta couche dans ``ref_geo.l_area`` correspondant au type de zonage que tu utilises comme unités géographiques.

Au niveau de GeoNature, cela s'appuie sur la vue ``gn_synthese.v_color_taxon_area`` qui interroge la table ``gn_synthese.cor_area_taxon`` qui est alimenté par un trigger sur la table ``gn_synthese.synthese``. Voir https://github.com/PnX-SI/GeoNature/issues/617.

**Comment by ClaireLagaye** [comment]
Oui c'est bien ce que j'ai fait, ça fonctionnait dans ma version précédente, je voyais bien les couleurs avec les dates.
Sur cette nouvelle version, j'ai la même couche l_area, les mêmes données, le même geojson mais je ne vois pas les couleurs dans occtax mobile et ne sais pas comment trouver où ça coince

**Comment by camillemonchicourt** [comment]
OK alors il y a peut-être un problème au niveau de la synchronisation des données car pas de changement au niveau de GeoNature sur ce point.
