### ISSUE TITLE
Problème sur la remontée des taxons

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_core#13]
En faisant des tests plus approfondis, j'ai l'impression que quelque chose coince dans la synchronisation de la liste de noms de taxons.

Dans taxhub, ma liste (id=500) contient **5215** noms, comme vu ici
http://5.196.209.136/taxhub/#!/listes/500
En BDD, dans la vue v_taxef_all_listes, j'ai bien aussi 5215 noms pour la liste 500

Quand je synchronise avec Sync, il me dit qu'il a synchronisé **7994** taxons
Quand j'ouvre Occtax sur le mobile il trouve **4050** taxons et il en manque (je ne trouve pas par exemple le Lagopède alpin, cd_nom=2951)

J'ai examiné ce que remonte la route http://5.196.209.136/taxhub/api/taxref/allnamebylist/500?limit=10000
Cette route remonte **9537** objets
Le lagopède n'y est pas et j'ai beaucoup de doublons. Ce ne sont pas des doublons parfaits, j'ai l'impression qu'il y a une fois le taxon avec un search_name = "nom_vern = nom_valide - cd_nom" et une fois avec search_name = "lb_nom = nom_valide - cd_nom"

Par exemple
```
{
    "cd_nom": 118158,
    "search_name": "Rosa elliptica =  <i> Rosa elliptica Tausch, 1819</i> - [ES - 118158]",
    "cd_ref": 118158,
    "nom_valide": "Rosa elliptica Tausch, 1819",
    "lb_nom": "Rosa elliptica",
    "regne": "Plantae",
    "group2_inpn": "Angiospermes",
    "id_liste": 500
  },
  {
    "cd_nom": 118158,
    "search_name": "Rosier à folioles elliptiques =  <i> Rosa elliptica Tausch, 1819</i> - [ES - 118158]",
    "cd_ref": 118158,
    "nom_valide": "Rosa elliptica Tausch, 1819",
    "lb_nom": "Rosa elliptica",
    "regne": "Plantae",
    "group2_inpn": "Angiospermes",
    "id_liste": 500
  }
```
Dans occtax mobile, si je cherche pour cet exemple Rosa elliptica, il ne me propose bien qu'un taxon Rosier à folioles elliptiques =  <i> Rosa elliptica Tausch, 1819</i> - [ES - 118158]

**Comment by camillemonchicourt** [comment]
Oui c'est normal d'avoir plusieurs fois les mêmes espèces dans la liste, avec ou sans nom français et avec les synonymes. En lien avec https://github.com/PnX-SI/TaxHub/issues/216 ?
Voir le fonctionnement expliqué ici : https://si.ecrins-parcnational.com/blog/2019-01-fuzzy-search-taxons.html

La route en question se base sur la table ``taxonomie.vm_taxref_list_forautocomplete`` alimentée par trigger.

**Comment by ClaireLagaye** [comment]
OK merci @camillemonchicourt  pour ces explications
Ma vue taxonomie.vm_taxref_list_forautocomplete avait des doublons voire des triplons (mais surement de ma faute avec mes copies de données entre bases). Une fois nettoyée, j'ai **9537** enregistrements pour ma liste 500. Le lagopède y est bien.
La route remonte également 9537 objets, le lagopède y est également
Dans occtax mobile j'ai maintenant **4680** taxons mais le lagopède n'y est pas
Y a-t-il quelque part des logs pour la synchronisation? Tout a l'air de bien se passer pourtant

**Comment by camillemonchicourt** [comment]
On vient de revoir le fonctionnement de cette VM dans TaxHub et on prépare la prochaine de release de TaxHub qui intégrera aussi le passage à Taxref v13 : https://github.com/PnX-SI/TaxHub/issues/219

Cela évitera les doublons, mais la route de TaxHub ne change pas pour ne pas devoir faire des modifications de GeoNature et Occtax-mobile.

**Comment by ClaireLagaye** [comment]
Tout paraît fonctionner en 0.3.1
