### ISSUE TITLE
Pouvoir déclencher la synchronisation manuellement

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_core#18]
L'application de synchronisation lance des synchro à certains démarrages mais pas à tous. Quand on modifie la config on ne peut pas déclencher une synchronisation "à la demande". 

Il serait intéressant qu'on puisse déclencher une synchro sur demande, en cliquant sur la pastille ou quelque chose du genre. A l'heure actuelle pour les tests, je dois régulièrement désinstaller/réinstaller l'application (je n'ai rien trouvé d'autre pour le moment)

**Comment by camillemonchicourt** [comment]
La synchronisation se fait quand on relance l'application, voila ce qu'a indiqué @sgrimault sur le fonctionnement : 

> La mise à jour des fichiers de paramétrage est de la responsabilité de l'application "Sync". Si entre temps, on souhaite les mettre à jour coté GeoNature, il suffit simplement de relancer "Sync" pour qu'elle en profite de faire cette mise à jour le cas échéant. C'est transparent, (rien de visible à l'écran) et le fait lors de la synchronisation. Le workflow actuel est le suivant :
> * GET -> /api/gn_commons/t_mobile_apps appelée en premier pour déterminer si il y a de nouvelle mise à jour des applications (vérification par package et du numéro de version), mise à jour automatique des fichiers de paramétrage uniquement si les applications sont effectivement présentes sur le terminal
> * en parallèle, synchronisation des données issues de GeoNature et synchronisation des relevés prêts à être envoyés. Pour éviter de trop "spammer" GeoNature, la synchronisation des données n'est pas systématique, j'ai fixé à une heure minimum entre deux synchronisations, par contre la synchronisation des relevés se fait sans contrainte (hormis accès à Internet).
