### ISSUE TITLE
Le SRID est un paramètre

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/gn_mobile_core#2]
Dans GN2 le SRID est un paramètre global disponible dans la table `gn_communs.t_parameters`.
Il doit être utilisé pour toute écriture dans les champs `the_geom_local`

**Comment by TheoLechemia** [comment]
De manière générale, il y aura des infos à récupérer dans cette table. Je pense notamment à la version de taxref, présente dans le standard occurrence de taxon et dont l'info est récupérée ici.
A renvoyer par l'API coeur ou celle d'occtax ?
