### ISSUE TITLE
Synchro et problème de mise à jour des données

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_core#21]
Je fais pointer l'application sur une liste composée de 500.000 taxons, ils se synchronisent sur l'appareil.
Ensuite je change le fichier de configuration de l'application pour pointer sur une liste plus réduite de 9000 taxons.
Lors de la synchronisation il indique bien qu'il synchronise les 9000 taxons, mais sur l'étape de la saisie de taxon d'Occtax, il m'affiche toujours les 500.000 taxons.
Problème de mise à jour ? De suppression des taxons qui ne devraient plus être proposés ?

**Comment by camillemonchicourt** [comment]
Il continue à synchroniser à chaque un peu plus de 9000 taxons, mais à m'afficher plus de 500.000 taxons à l'étape 3.
Donc je ne sais pas si quand la liste de taxons change, la synchro n'est pas effective, ou si il ne supprime pas les taxons synchronisés précédemment ?

**Comment by sgrimault** [comment]
Effectivement, lors de la synchronisation, il met à jour les données si elles sont déjà présentes et ajoute celles manquantes mais rien n'est supprimé.
Dans le cas où on change de configuration qui fait pointer sur une liste plus réduite des taxons, on aura du coup aussi les autres taxons déjà synchronisés.
Je propose donc pour faire simple, de vider à chaque fois les données locales lors de la synchronisation, si celle-ci retourne bien des nouvelles données.

**Comment by camillemonchicourt** [comment]
Oui OK bien vu.
Mais en effet seulement si il y a des nouvelles données pour pas que ça resynchronise toutes les données à chaque fois.
Merci.

**Comment by camillemonchicourt** [comment]
J'ai fait une liste avec 9500 noms.
Je supprime plusieurs noms dans TaxHub et en ajoute aussi 3 à la liste.
Ma liste contient désormais 9481 noms.
Je relance Sync-mobile puis Occtax-mobile. 
J'ai désormais 9503 noms.

Il a donc bien ajouté les 3 noms, mais à priori pas supprimé ceux que j'ai retiré de la liste.

**Comment by camillemonchicourt** [comment]
OK corrigé avec la 1.1.1 de Sync-mobile et la 1.1.3 d'Occtax-mobile
