### ISSUE TITLE
Pb de connexion

### ISSUE THREAD

**Issue by CistudeNature** [PnX-SI/gn_mobile_core#22]
J'ai installé la version sync-1.0.0-generic-release.apk et lorsque je clique sur l'icone de l'application un écran blanc s'affiche et disparaît immédiatement.
En contrôlant les logs , j'ai le message d'erreur suivant 
C:\Users\S227098>adb logcat | findstr fr.geonature.sync|findstr URL
07-28 08:26:04.842 14745 14745 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.geonature.sync/fr.geonature.sync.ui.home.HomeActivity}: java.lang.IllegalArgumentException: Invalid URL host: "obs-nature.org "
07-28 08:26:07.310 14814 14814 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.geonature.sync/fr.geonature.sync.ui.home.HomeActivity}: java.lang.IllegalArgumentException: Invalid URL host: "obs-nature.org "
07-28 08:26:08.722 14853 14853 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.geonature.sync/fr.geonature.sync.ui.home.HomeActivity}: java.lang.IllegalArgumentException: Invalid URL host: "obs-nature.org "
07-28 08:26:10.171 14900 14900 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.geonature.sync/fr.geonature.sync.ui.home.HomeActivity}: java.lang.IllegalArgumentException: Invalid URL host: "obs-nature.org "
07-28 08:26:11.105 14940 14940 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.geonature.sync/fr.geonature.sync.ui.home.HomeActivity}: java.lang.IllegalArgumentException: Invalid URL host: "obs-nature.org "

Les différentes API fonctionnent correctement.

J'ai désinstallé et résinstallé l'application et j'ai toujours le même problème. J'ai du mal à identifier où est stocké cette URL.

merci d'avance pour votre retour

**Comment by camillemonchicourt** [comment]
Oui les logs sont assez explicites : "Invalid URL host: "obs-nature.org "

Dans les paramètres de Sync-mobile, il faut bien renseigner l'URL complète de votre GeoNature et de votre TaxHub.
Avec le HTTPS devant et le chemin complet jusqu'à GeoNature.

**Comment by camillemonchicourt** [comment]
Donc à remplacer par https://obs-nature.org/geonature et https://obs-nature.org/taxhub

**Comment by CistudeNature** [comment]
Ci-dessous le fichier settings_sync.json que j'utilise. Ce qui est étrange! après une résinstallation sans avoir copier le fichier settings_sync.json , j'ai le même message erreur.  Après une désinstallation, j'arrête et je redémarre le mobile.
{
  "geonature_url":  "https://www.obs-nature.org/geonature",
  "taxhub_url":  "https://www.obs-nature.org/taxhub",
  "uh_application_id": 1,
  "observers_list_id": 1,
  "taxa_list_id": 100,
  "code_area_type": "M1",
  "page_size": 100,
  "page_max_retry": 5
}

**Comment by camillemonchicourt** [comment]
Oui étonnant. Mais il y a 2 manières de gérer les fichiers de configuration. Directement sur le mobile ou en le centralisant sur le serveur GeoNature (méthode la plus simple, voir la documentation d'installation). 
Dans votre URL, le www semble de trop ?

**Comment by camillemonchicourt** [comment]
Vous avez pu faire fonctionner l'application ?
