### ISSUE TITLE
Authentification module Sync

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/gn_mobile_core#24]
Lors de l'identification au module sync, lorsqu'un utilisateur entre son identifiant et son mot de passe, le message _authentification réussie_ apparait mais il faut saisir une nouvelle fois l'identifiant et le mdp pour se connecter avec son compte.

**Comment by sgrimault** [comment]
Difficile à reproduire car pas systématique.
Je ferai des ajustements sur la partie authentification lors des prochaines évolutions à venir.

**Comment by camillemonchicourt** [comment]
J'ai toujours le soucis avec la version 1.1.1. Il faut souvent saisir 2 fois son login et mot de passe pour que l’authentification fonctionne.
