### ISSUE TITLE
Synchronisation des données unité géographique : manque message

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_mobile_core#30]
Lorsque l'on réalise une synchro, les messages s'arrètent à "Synchronisation des taxons" or après cette étape il y a la récupération des données par unité géographique. Qui est pour le coup très longue.

![image](https://user-images.githubusercontent.com/3088650/102591521-6f73aa00-4112-11eb-94a1-2f3d627a5c5c.png)

**Comment by camillemonchicourt** [comment]
Oui idem le message devrait ensuite indiquer qu'il synchronise les unités géographiques car c'est la partie la plus longue mais elle n'est pas explicite.
