### ISSUE TITLE
Problème synchronisation 

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_core#32]
Bonjour,
Une utilisatrice vient de remonter un problème avec l'application sur mobile.
1) une saisie effectuée le 19/01/2021 n'a pas été remonté dans l'application userhub.
ps : nous avons vérifié en faisant en live une saisie bidon et à priori tout fonctionne puisque la synchronisation s'est effectuée et nous avons constaté l'apparition de la donnée dans Geonature.
sur le téléphone dans le répertoire /storage/emulated/0/Android/data/fr.geonature.occtax/inputs j'ai trouvé le fichier json contenant la saisie effectuée.
Il est en pièce jointe.

J'ai tenté de modifier le fichier en remplaçant la valeur id_nomenclature_obs_meth dans le fichier par id_nomenclature_obs_technique comme indiqué dans 1 issue précédente comme solution dans le cas de blocage de la synchro.
Cela n'a pas fonctionné.
Peut-on récupérer cette saisie ? et comment ?

2) Cette utilisatrice m'a aussi indiqué la disparition pure et simple de certaines saisies. Je n'ai pas trouvé trace ni en base sous Geonature dans la table synthese, ni dans le répertoire input d'occtax sur le téléphone.
Pourtant à cette date le 23/09/2020 en l'occurence, d'autres saisies ont été parfaitement intégrées.
Auriez-vous une explication sur l'origine du problème ? Y a t-il moyen de vérifier sur le téléphone ce qu'il s'est passé ?
(trace dans la base sqlite, log ou fichier ....)
D'avance merci,
Christian Bièche
Cistude Nature
Pour info, nous sommes toujours sur une version geotnature 2.4.1 et une version téléphone occtax-1.0.0-generic-release.apk
[input_occtax_159449322.zip](https://github.com/PnX-SI/gn_mobile_core/files/5944695/input_occtax_159449322.zip)

**Comment by camillemonchicourt** [comment]
Une saisie n'est pas remontée dans UsersHub ? Plutôt dans GeoNature, non ?
Les changements de obs_methode en obs_technique sont intervenus dans GeoNature 2.5.0.
Du coup si vous êtes en GeoNature 2.4, je ne comprends pas ce que vous avez renommé et pourquoi ?
Je ne vois pas de soucis dans le JSON, mais je ne maitrise pas en détail le sujet pour l'identifier.

Il faudrait plutôt voir dans les logs de GeoNature si il y a des erreurs indiquées au moment de la synchronisation des données.

Il y a eu beaucoup d'améliorations depuis Occtax-mobile 1.0.0 et GeoNature 2.4, donc pas évident de revenir sur des versions anciennes.

Mais si vous avez plus de logs et détails sur les problèmes, on pourra peut-être mieux identifier le soucis ?

**Comment by christianbieche** [comment]
Oui bien sûr Geonature :-)
Euh simplement parce que j'ai trouvé comme je l'ai dit une réponse dans 1 issue qui semblait corriger un blocage en faisant cette modification. J'ai mal lu sans puisque visiblement ce n'est pas pour la bonne version.
Je vais voir si je peux récupérer les logs du téléphone à cette date et regarder les logs Geonature effectivement (mais je pensais plutôt un problème sur l'application téléphonique)
Merci en tout cas.

**Comment by camillemonchicourt** [comment]
A votre place, je privilégierai de vous mettre à jour au niveau de GeoNature et Occtax-mobile et de voir si vous reproduisez les problèmes une fois à jour.

**Comment by christianbieche** [comment]
Effectivement c'est ce que je prévois de faire.
Cela peut effectivement solutionner quelques problèmes.
