### ISSUE TITLE
Impossible de synchroniser les données

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_mobile_core#35]
Bonjour,
J'ai de nouveau des problèmes de synchronisation entre les saisies sur le téléphone et la mise à jour dans geonature.
Les synchronisation ne se font pas 👎 
Dans le log sur le téléphone on a 
04-14 12:19:26.943 10621 10664 D OkHttp  : --> POST https://ra-na.fr/geonature//api/occtax/releve (1494-byte body)
04-14 12:19:27.268 10621 10664 D OkHttp  : <-- 500 INTERNAL SERVER ERROR https://ra-na.fr/geonature//api/occtax/releve (324ms, 36-byte body)
Et sur le log de geonature nous avons 

[SQL: INSERT INTO pr_occtax.t_occurrences_occtax (id_releve_occtax, id_nomenclature_obs_technique, id_nomenclature_bio_condition, id_nomenclature_bio_status, id_nomenclature_naturalness, id_nomenclature_exist_proof, id_nomenclature_observation_status, id_nomenclature_blurring, id_nomenclature_source_status, determiner, id_nomenclature_determination_method, id_nomenclature_behaviour, cd_nom, nom_cite, meta_v_taxref, sample_number_proof, digital_proof, non_digital_proof, comment, unique_id_occurence_occtax) VALUES (%(id_releve_occtax)s, %(id_nomenclature_obs_technique)s, %(id_nomenclature_bio_condition)s, %(id_nomenclature_bio_status)s, %(id_nomenclature_naturalness)s, %(id_nomenclature_exist_proof)s, %(id_nomenclature_observation_status)s, %(id_nomenclature_blurring)s, %(id_nomenclature_source_status)s, %(determiner)s, %(id_nomenclature_determination_method)s, %(id_nomenclature_behaviour)s, %(cd_nom)s, %(nom_cite)s, (SELECT gn_commons.get_default_parameter(%(get_default_parameter_2)s) AS get_default_parameter_1), %(sample_number_proof)s, %(digital_proof)s, %(non_digital_proof)s, %(comment)s, (SELECT uuid_generate_v4() AS uuid_generate_v4_1)) RETURNING pr_occtax.t_occurrences_occtax.id_occurrence_occtax]
[parameters: {'id_releve_occtax': 6098, 'id_nomenclature_obs_technique': None, 'id_nomenclature_bio_condition': 158, 'id_nomenclature_bio_status': 29, 'id_nomenclature_naturalness': 161, 'id_nomenclature_exist_proof': 81, 'id_nomenclature_observation_status': None, 'id_nomenclature_blurring': None, 'id_nomenclature_source_status': None, 'determiner': None, 'id_nomenclature_determination_method': 446, 'id_nomenclature_behaviour': None, 'cd_nom': 444432, 'nom_cite': 'Lissotriton helveticus', 'get_default_parameter_2': 'taxref_version', 'sample_number_proof': None, 'digital_proof': None, 'non_digital_proof': None, 'comment': None}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2021-04-14 12:19:46 +0200] [26962] [ERROR] (psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte ****NOT NULL de la colonne « id_nomenclature_obs_technique** »**
DETAIL:  La ligne en échec contient (10083, 754b60c9-adc9-4f22-a775-e7d4c1b47379, 6099, null, 158, 29, 161, 81, null, null, null, null, null, 446, 444436, Pelophylax, Taxref V11.0, null, null, null, null, null)

[SQL: INSERT INTO pr_occtax.t_occurrences_occtax (id_releve_occtax, id_nomenclature_obs_technique, id_nomenclature_bio_condition, id_nomenclature_bio_status, id_nomenclature_naturalness, id_nomenclature_exist_proof, id_nomenclature_observation_status, id_nomenclature_blurring, id_nomenclature_source_status, determiner, id_nomenclature_determination_method, id_nomenclature_behaviour, cd_nom, nom_cite, meta_v_taxref, sample_number_proof, digital_proof, non_digital_proof, comment, unique_id_occurence_occtax) VALUES (%(id_releve_occtax)s, %(id_nomenclature_obs_technique)s, %(id_nomenclature_bio_condition)s, %(id_nomenclature_bio_status)s, %(id_nomenclature_naturalness)s, %(id_nomenclature_exist_proof)s, %(id_nomenclature_observation_status)s, %(id_nomenclature_blurring)s, %(id_nomenclature_source_status)s, %(determiner)s, %(id_nomenclature_determination_method)s, %(id_nomenclature_behaviour)s, %(cd_nom)s, %(nom_cite)s, (SELECT gn_commons.get_default_parameter(%(get_default_parameter_2)s) AS get_default_parameter_1), %(sample_number_proof)s, %(digital_proof)s, %(non_digital_proof)s, %(comment)s, (SELECT uuid_generate_v4() AS uuid_generate_v4_1)) RETURNING pr_occtax.t_occurrences_occtax.id_occurrence_occtax]
[parameters: {'id_releve_occtax': 6099, 'id_nomenclature_obs_technique': None, 'id_nomenclature_bio_condition': 158, 'id_nomenclature_bio_status': 29, 'id_nomenclature_naturalness': 161, 'id_nomenclature_exist_proof': 81, 'id_nomenclature_observation_status': None, 'id_nomenclature_blurring': None, 'id_nomenclature_source_status': None, 'determiner': None, 'id_nomenclature_determination_method': 446, 'id_nomenclature_behaviour': None, 'cd_nom': 444436, 'nom_cite': 'Pelophylax', 'get_default_parameter_2': 'taxref_version', 'sample_number_proof': None, 'digital_proof': None, 'non_digital_proof': None, 'comment': None}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2021-04-14 12:26:54 +0200] [26962] [ERROR] (psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « id_dataset »
DETAIL:  La ligne en échec contient (6101, cd2c2acd-8730-4ba7-ab88-48ac4242bf86, null, 51, null, null, null, 2021-01-19 10:28:42, 2021-01-19 10:28:42, null, null, 21, 21, mobile, null, 01010000206A080000C90791E933161941A83B666926855841, 0101000020E6100000000000C0B529E5BF406A64BFCD714640, null, null, null, null, null, null, null)

on essaye d'insérer des valeurs nulles dasn des tables et cela ne passe pas.

Cependant si je regarde le contenu d'un  json envoyé on a
"id_nomenclature_obs_technique": 41,
par contre effectivement  on a 
"id_dataset": null,

Mon utilisatrice a 28 saisies dans son téléphone qui attende la remontée et cela a déjà fonctionné car elle a abandonné la saisie papier.
Quel est le problème, comment résoudre et comment récupérer les saisies ??

RQ01 : étrangement contrairement à d'autres utilisateurs l'application ne s'est pas mise à jour sur son téléphone.
Je viens de le faire manuellement mais le problème persiste.
J'ai tenté une saisie après la mise à jour mais pas mieux. Cela plante toujours 👎 

RQ02  : pour d'autres utilisateurs avec les même paramètres cela fonctionne.
Est  ce que si je dépose les fichiers json sur un autre téléphone on pourra faire la synchronisation ???

Christian Bièche
Cistude Nature

RQ03 : cela m'inquiète car j'ai de plus en plus d'utilisateurs avec ces applications mais si elle ne fonctionnent pas !
le but est de gagner du temps et de ne pas faire des saisies en double.
je pensais qu'avec la version geonature en 2.5.5, taxhub en 1.7.3 et les applications telephone SYNC 1.1.2 et OOCTAX 1.1.4
cela marcherait mieux....

**Comment by christianbieche** [comment]
Je corrige. Finalement, la saisie que j'ai effectuée ce matin a fini par arriver sur le serveur c'est donc probablement un problème de contenu qui a changé entre les versions ?

**Comment by christianbieche** [comment]
Effectivement, j'ai récupéré un json avant sur 1 autre téléphone et j'ai pu comparer les 2 fichiers.
Ils sont différents et il manque certaines données.
En remodifiant le fichier j'ai pu remonter les informations dans la base.
Il y a donc des différences entre les fichiers pour les versions ou bien c'est autre chose ?
Cela voudrait dire aussi qu'entre 2 versions différentes il y a des risques non négligeable de perte de données.
il faudrait prévoir du coup le problème.

**Comment by camillemonchicourt** [comment]
Il y a bien un changement majeur entre la version 2.4 et 2.5 de GeoNature avec le renommage du champs "Méthode d'observation" en "Technique d'observation", qui est lié à un renommage dans le standard du SINP.
C'est bien spécifique, indiqué dans les notes de version de GeoNature (https://github.com/PnX-SI/GeoNature/releases/tag/2.5.0), mais aussi dans celles de Occtax-mobile, qu'il faut faire attention à ce passage. Et ne pas essayer de synchroniser des données vers un GeoNature en 2.5 ou plus depuis une version d'Occtax-mobile inférieure à la 1.1.0.

Évoqué ici : https://github.com/PnX-SI/gn_mobile_occtax/issues/79

On fait en sorte que tout cela reste bien compatible, mais là il y a eu un renommage de champs au niveau du standard du SINP, donc on a du s'y aligner.
Hormis ce cas particulier avec la version 2.5 de GeoNature, il n'y a pas de raison d'incompatibilité similaire lors de nouvelles versions.

Mais là en regardant les erreurs renvoyés, on dirait que le problème est en partie différent. Il essaie de poster une observation sans ``id_dataset`` et comme ce champs est obligatoire, ça coince, là je vois pas comment c'est possible. Sauf si vous avez eu le soucis de synchronisation des jeux de données discuté dans un autre ticket ?

**Comment by christianbieche** [comment]
Merci de ta réponse Camille. C'est plus clair.

Alors j'ai fini par synchroniser les fichiers json en les modifiant un par un.
1) pour le premier il y a des choses bizarre puisque l'id_dataset était à null et ce n'était pas le cas pour tous les autres !
Mystère.
2) pour tous les autres, le problème était due probablement au changement de version.
Dans les fichiers on avait "id_nomenclature_obs_meth": 41 au lieu de "id_nomenclature_obs_technique": 41
Une fois cela corrigé tous les fichiers json ont été synchronisés.

Par rapport à la remarque, sur les versions et les comptabilités. Je ne maîtrise malheureusement pas les saisies sur le terrain et le problème risque de ce reproduire. Là je m'en suis sortie car peu de saisie mais cela risque de ne pas être toujours le cas.
Il faudrait trouver un moyen de pouvoir manuellement en récupérant les json faire la mise à jour en base.
C'est beaucoup trop impactant pour les naturalistes sur le terrain.
Visiblement je ne peux pas figer les versions trop longtemps non plus.

**Comment by camillemonchicourt** [comment]
On ne prévoit de changer des noms de champs. :-)
