### ISSUE TITLE
Authentification impossible dans Sync 1.2.0

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_core#38]
Bonjour,
je suis en train de tester la version 1.2.0 (avec un geonature 2.6.2) et sur la majorité des appareils, j'ai une impossibilité de connexion.
Le login semble réussir, Sync renvoie "Authentification réussie" mais une seconde après il retourne à l'écran de login avec le message "Non connecté"
Ce qui est étrange c'est que sur certains appareils, l'authentification marche à chaque fois, sur d'autres jamais et sur un petit nombre, c'est aléatoire
Voici le log obtenu et une capture d'écran du comportement
[log_sync.txt](https://github.com/PnX-SI/gn_mobile_core/files/6693218/log_sync.txt)

https://user-images.githubusercontent.com/11782642/122905821-d8520e00-d351-11eb-8e23-196f455f1555.mp4

**Comment by xavyeah39** [comment]
Bonjour Claire,
Nous avons rencontré exactement le même soucis chez certains PNR AURA où nous déployons en phase de test actuellement.
Nous avons fini par parvenir à rester connecté après de multiples tentatives (où nous avons aussi tenté de rétrograder sur les pre-release antérieures (1.1.9 et 1.1.8) mais le problème persistait).
A force de manip je ne sais pas vraiment si c'est ça qui a réglé le soucis mais nous avons testé de : vider le cache et les données de l'application (via paramètres >> applications) puis désinstallé et réinstallé complétement sync (en 1.2.0). 
Désormais ça fonctionne. On peut s'authentifier normalement puis lancer une synchro.
Peut-être un soucis dans la gestion du cache ou des cookies de l'appli ?

**Comment by ClaireLagaye** [comment]
Merci @xavyeah39 
J'ai essayé ta méthode sur un appareil tout neuf qui refuse systématiquement l'authentification -> Pas de résultat
En remontant les versions, il semble que ça fonctionne (j'ai testé sur 2 mobiles récalcitrants) jusqu'à la version 1.1.5
Même sur un mobile où l'authentification fonctionne bien en <=1.1.5, dès que je monte en version, j'ai de nouveau le même problème.

**Comment by xavyeah39** [comment]
Je viens de retester d'installer la 1.2.0 sur mon smartphone ou je fais pas mal de tests sur différentes instances et avec différentes versions et avec encore un comportement un peu différent mais semblable (pour info je suis sur android 9).

En réinstallant la 1.2.0 sans vider le cache ni supprimer les données de l'appli au préalable, pas moyen de me connecter. Une erreur est levé _"Erreur lors du chargement des paramètres settings_sync.json"_ lorsque la page d'authentification apparait. 
Avant d'avoir eu le temps de commencer à saisir les identifiants, je suis renvoyé à la page d'accueil où les options "Synchroniser..." et "Se connecter" sont désormais grisées. Je ferme complétement l'appli, je la relance = pareil.

Comme mon fichier de settings et correctement nommé coté serveur et s'appelle `settings.json` et non `settins_sync.json` comme dans le message d'erreur j'ose tenter d'en déduire que :
Tant qu'on est pas authentifié, on ne récupère pas le bon settings.json côté serveur
Du coup c'est le fichier de settings embarqué par défaut dans l'apk qui semble s'exécuter et comme il s'appelle `settings_sync.json` ça foire ?
Si pour toi ça fonctionne en 1.1.5, c'est peut être lié aux évolutions dans les versions intermédiaires comme _"Lancement automatique de la synchronisation et mise à jour des fichiers de paramétrage lors de la toute première authentification."_ ([1.1.8](https://github.com/PnX-SI/gn_mobile_core/releases/tag/1.1.8)) 
Ou encore _"La gestion des cookies a été un peu changée de façon à pouvoir déterminer plus tôt si la session reste valide ou non."_ ([1.1.7](https://github.com/PnX-SI/gn_mobile_core/releases/tag/1.1.7)) 
Qu'en pensez-vous ? 

En tout cas, simplement en vidant le cache et en supprimant les données de l'appli (sans même la réinstaller) je confirme que ça fonctionne bien à nouveau chez moi.

**Comment by xavyeah39** [comment]
Merci @sgrimault, 
J'ai refais des tests dans cet ordre : 

TEST 1 : upgrade de la version courante installée (1.2.0) via la conf centralisé : 
1 - je télécharge l'apk sur le serveur geonature et je met à jour la table `gn_commons.t_mobile_apps` pour activer la màj en 1.2.1
2 - je ferme sync complétement, je ne supprime pas le cache ni les données, je relance l'appli => ECHEC la mise à jour ne met pas proposé et toujours l'erreur : "Erreur lors du chargement des paramètres settings_sync.json"
3 - je ferme l'appli, je vide cache et données, je relance => Pas mieux...
VERDICT : la màj centralisé ne fonctionne pas.

Je poursuit le test en désinstallant réinstallant

TEST 2 : upgrade de la version courante installée (1.2.0) manuellement (desinstall/reinstall) : 
1 - vidage du cache et suppression des données de l'appli courante installée (via paramètres>applications>sync>stockage) 
2 - désinstallation
3 - Téléchargement et install de la nouvelle apk (1.2.1)
Au lancement toujours le même soucis : pas moyen de s'authentifier ni de lancer une synchro (grisé) en revanche les paramètres des URLs sont toujours pré-remplis et toujours la même erreur de levée au lancement de l'appli  : "Erreur lors du chargement des paramètres settings_sync.json"
4 - vidage du cache et suppression des données de l'appli courante installée (via paramètres>applications>sync>stockage) 
5 - je relance l'appli et là c'est bon : on me propose d'abord de renseigner les paramètres des URLs (qui ont bien été vidés cette fois) puis de me connecter. Authentification réussie -> la synchro se lance normalement.

Chez moi (Samsung S7 en android 9) ce n'est pas mieux donc...
Je n'ai pas d'autre terminal plus récent sous la main pour faire un éventuel lien avec la version d'android et je n'ai pas eu le temps de passer en debug adb pour regarder les logs.
++

**Comment by camillemonchicourt** [comment]
Oui il faudrait certainement des logs. Voir la doc qui indique comment les récupérer

**Comment by camillemonchicourt** [comment]
Merci aux testeurs de confirmer que c'est OK avec la version 1.3.0 de Sync-mobile, branchée à une version 2.7.5 de GeoNature ?

**Comment by DonovanMaillard** [comment]
Problème reproduit sur la 1.2.x sur mon appareil, non reproduit sur la 1.3.0.
