### ISSUE TITLE
Mise à jour automatique ne se fait pas Sync 1.2.1

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_core#39]
A l'ouverture d'un Sync inférieur, il identifie bien qu'il y a une version plus récente mais quand on accepte l'installation, rien ne se fait et il ouvre une fenêtre d'authentification
La version de sync ne change pas 
Problème soulevé par @xavyeah39 et reproduit sur différents appareils au Parc de la Vanoise
https://github.com/PnX-SI/gn_mobile_core/issues/38#issuecomment-867430901

**Comment by sgrimault** [comment]
Bonjour @ClaireLagaye,

Pourrais tu me fournir des logs pour voir un peu ce qu'il se passe ?
Le problème rencontré viendrait d'une ancienne version de l'application de synchronisation (<1.2.1, laquelle ?) qui lance la procédure de mise à jour vers la version 1.2.1.

La route appelée pour télécharger l'APK correspondant n'est pas protégée (par exemple, on peut accéder directement à https://demo.geonature.fr/geonature/api/static/mobile/occtax/occtax-1.2.0-generic-debug.apk sur l'instance de démonstration de GeoNature), donc je ne vois pas pourquoi on est redirigé vers l'écran d'authentification.

**Comment by ClaireLagaye** [comment]
Voici le log @sgrimault 
On dirait qu'il commence à télécharger mais ça n'avance pas et revient à l'écran de login[
[log_sync.txt](https://github.com/PnX-SI/gn_mobile_core/files/6733942/log_sync.txt)
](url)

**Comment by camillemonchicourt** [comment]
Merci aux testeurs de confirmer que c'est OK avec la version 1.3.0 de Sync-mobile, branchée à une version 2.7.5 de GeoNature ?
