### ISSUE TITLE
Impossibilité de charger Sync

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/gn_mobile_core#4]
J'essaye d'installer sync 0.1.3 comme je l'avais fait auparavant

- Install de l'apk

- Copie du data.db dans le dossier Android/data/fr.geonature.sync/databases 

Mais ça ne fonctionne pas (aucun observateur ni taxon ne remonte).
J'ai vu que cette nouvelle release permettait de se connecter sur un geonature 2. Est-il nécessaire de le faire?
Nous n'avons pas de geonature 2 pour l'instant et je voulais surtout tester OccTax sur mobile (ce que je ne peux pas faire si je n'ai pas d'observateurs qui remontent avec Sync)

**Comment by camillemonchicourt** [comment]
Oui de ce que j'ai compris il faut le connecter à un GeoNature 2.
Tu peux tenter de le connecter au serveur de démo : http://demo.geonature.fr

**Comment by ClaireLagaye** [comment]
Merci @camillemonchicourt ça fonctionne en effet comme ça. 
Je me suis branchée sur votre serveur de démo, ça fonctionne bien !

**Comment by sgrimault** [comment]
Depuis la version 0.0.9, l'application "Sync" se synchronise toute seule sur une instance de GeoNature v2 que vous pouvez paramétrer depuis les paramètres de l'application.
