### ISSUE TITLE
Problèmes authentifications

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_core#42]
Bonjour, un retour après quelques tests : 

- La connexion a une instance de geonature sans domaine (ip seulement) est impossible : sync ne propose pas à l'utilisateur de "se connecter" : le bouton est grisé
- La connexion à une instance avec un domaine non certifié (http) est possible pour l'utilisateur, mais sync n'arrive pas à lister les applications compatibles. 
- Une fois l'instance sur un domaine certifié, connexion possible mais pour le moment, récupération impossible des datasets (en train de creuser pour voir si ca vient de geonature coté serveur ou du mobile).

Tout ça sera à revoir lors de la refonte vers l'application mobile v2 pour être moins bloquant.

**Comment by camillemonchicourt** [comment]
Le troisième soucis venait d'un changement dans la branche develop de GeoNature, revu en vue de la 2.9.0 de GN à venir

**Comment by DonovanMaillard** [comment]
Oui.  nécessitera d'être revu quand meme dans le mobile pour s'adapter aux évolutions de geonature

**Comment by sgrimault** [comment]
Bonjour,

Est ce que c'est encore d'actualité suite à la publication de la version 2 de Occtax ?
Pour information et dans tous les cas, Occtax refusera toujours d'accéder à un domaine sans HTTPS.

**Comment by camillemonchicourt** [comment]
Oui on peut fermer du coup.
