### ISSUE TITLE
Connexion / Déconnexion

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_core#7]
A priori actuellement quand on ferme l'application puis qu'on l'a rouvre, il faut se reconnecter.

Il serait intéressant de conserver l'application connectée le plus longtemps possible pour ne pas avoir à se reconnecter régulièrement.

Mais je ne sais pas ce qui est techniquement possible ?

**Comment by sgrimault** [comment]
Sur la version 0.2.2, c'est bien le cas. L'application garde en mémoire le token et redirige automatiquement sur la page de login si ce dernier à expiré (ou n'existe pas).

**Comment by camillemonchicourt** [comment]
La connexion est bien gardée.
