### ISSUE TITLE
settings_sync.json - Clarifier paramètres

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_mobile_core#9]
Pour clarifier les paramètres, je propose de les renommer comme cela, en cohérence avec GeoNature : 
- application_id > uh_application_id
- users_menu_id > observers_list_id
- taxref_list_id > taxon_list_id

**Comment by sgrimault** [comment]
`taxon_list_id` => `taxref_list_id` ou `taxa_list_id` histoire de rester cohérent sur le nommage ?

**Comment by camillemonchicourt** [comment]
Bien vu, alors ``taxa_list_id``, car c'est une liste de taxons, pas de Taxref. Merci.

**Comment by camillemonchicourt** [comment]
Fait dans la version 0.2.6
